import { supabase } from '../src/lib/supabase/client';

const products = [
  {
    name: 'Glucophage 500mg',
    description: 'Metformin hydrochloride tablets used for treating type 2 diabetes.',
    price: 45.00,
    mrp: 50.00,
    discount: 10,
    category: 'Medicines',
    subcategory: 'Diabetes',
    brandName: 'Merck',
    stockQuantity: 150,
    primaryImage: 'https://images.unsplash.com/photo-1584308666744-24d5e4a83350?auto=format&fit=crop&q=80&w=600',
    additionalImages: [],
    batchNumber: 'B1001',
    expiryDate: '2028-05-01',
    minStockLevel: 20,
    stockStatus: 'in-stock',
    healthConcern: 'Diabetes',
    status: 'published',
  },
  {
    name: 'Aspirin Protect 100mg',
    description: 'Low dose aspirin for cardiovascular protection and heart care.',
    price: 30.00,
    mrp: 35.00,
    discount: 14,
    category: 'Medicines',
    subcategory: 'Cardiovascular',
    brandName: 'Bayer',
    stockQuantity: 200,
    primaryImage: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&q=80&w=600',
    additionalImages: [],
    batchNumber: 'B1002',
    expiryDate: '2027-12-01',
    minStockLevel: 50,
    stockStatus: 'in-stock',
    healthConcern: 'Heart Care',
    status: 'published',
  },
  {
    name: 'Digene Antacid Gel',
    description: 'Fast relief from acidity and gas. Mint flavor.',
    price: 120.00,
    mrp: 135.00,
    discount: 11,
    category: 'Medicines',
    subcategory: 'Digestive Health',
    brandName: 'Abbott',
    stockQuantity: 80,
    primaryImage: 'https://images.unsplash.com/photo-1550572017-edb947c7c34d?auto=format&fit=crop&q=80&w=600',
    additionalImages: [],
    batchNumber: 'B1003',
    expiryDate: '2026-10-01',
    minStockLevel: 15,
    stockStatus: 'in-stock',
    healthConcern: 'Stomach Care',
    status: 'published',
  },
  {
    name: 'Liv.52 Tablets',
    description: 'Ayurvedic hepatoprotective medicine for liver care and detoxification.',
    price: 140.00,
    mrp: 150.00,
    discount: 6,
    category: 'Ayurvedic',
    subcategory: 'Supplements',
    brandName: 'Himalaya',
    stockQuantity: 300,
    primaryImage: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&q=80&w=600',
    additionalImages: [],
    batchNumber: 'B1004',
    expiryDate: '2027-08-01',
    minStockLevel: 30,
    stockStatus: 'in-stock',
    healthConcern: 'Liver Care',
    status: 'published',
  },
  {
    name: 'Volini Pain Relief Spray',
    description: 'Fast acting pain relief spray for joints and muscles.',
    price: 180.00,
    mrp: 200.00,
    discount: 10,
    category: 'Healthcare Devices & Supplies',
    subcategory: 'Pain Relief',
    brandName: 'Sun Pharma',
    stockQuantity: 120,
    primaryImage: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&q=80&w=600',
    additionalImages: [],
    batchNumber: 'B1005',
    expiryDate: '2026-11-01',
    minStockLevel: 25,
    stockStatus: 'in-stock',
    healthConcern: 'Bone, Joint & Muscle',
    status: 'published',
  },
  {
    name: 'Cystone Tablets',
    description: 'Helps in preventing and treating kidney stones.',
    price: 155.00,
    mrp: 170.00,
    discount: 8,
    category: 'Ayurvedic',
    subcategory: 'Supplements',
    brandName: 'Himalaya',
    stockQuantity: 90,
    primaryImage: 'https://images.unsplash.com/photo-1584308666744-24d5e4a83350?auto=format&fit=crop&q=80&w=600',
    additionalImages: [],
    batchNumber: 'B1006',
    expiryDate: '2028-01-01',
    minStockLevel: 15,
    stockStatus: 'in-stock',
    healthConcern: 'Kidney Care',
    status: 'published',
  },
  {
    name: 'Refresh Tears Eye Drops',
    description: 'Lubricant eye drops for dry eyes and eye care.',
    price: 130.00,
    mrp: 145.00,
    discount: 10,
    category: 'Medicines',
    subcategory: 'Eye Care',
    brandName: 'Allergan',
    stockQuantity: 210,
    primaryImage: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&q=80&w=600',
    additionalImages: [],
    batchNumber: 'B1007',
    expiryDate: '2026-09-01',
    minStockLevel: 40,
    stockStatus: 'in-stock',
    healthConcern: 'Eye Care',
    status: 'published',
  },
  {
    name: 'Asthalin Inhaler',
    description: 'Salbutamol inhaler for quick relief from asthma symptoms.',
    price: 165.00,
    mrp: 180.00,
    discount: 8,
    category: 'Medicines',
    subcategory: 'Respiratory',
    brandName: 'Cipla',
    stockQuantity: 150,
    primaryImage: 'https://images.unsplash.com/photo-1550572017-edb947c7c34d?auto=format&fit=crop&q=80&w=600',
    additionalImages: [],
    batchNumber: 'B1008',
    expiryDate: '2027-05-01',
    minStockLevel: 30,
    stockStatus: 'in-stock',
    healthConcern: 'Respiratory Care',
    status: 'published',
  },
  {
    name: 'Cetaphil Gentle Skin Cleanser',
    description: 'Daily facial cleanser for sensitive skin.',
    price: 320.00,
    mrp: 350.00,
    discount: 8,
    category: 'Personal Care',
    subcategory: 'Skincare',
    brandName: 'Galderma',
    stockQuantity: 85,
    primaryImage: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&q=80&w=600',
    additionalImages: [],
    batchNumber: 'B1009',
    expiryDate: '2027-10-01',
    minStockLevel: 20,
    stockStatus: 'in-stock',
    healthConcern: 'Skin Care',
    status: 'published',
  },
  {
    name: 'Shelcal 500',
    description: 'Calcium and Vitamin D3 supplement for bone health.',
    price: 110.00,
    mrp: 125.00,
    discount: 12,
    category: 'Vitamins & Supplements',
    subcategory: 'Minerals',
    brandName: 'Torrent Pharma',
    stockQuantity: 400,
    primaryImage: 'https://images.unsplash.com/photo-1584308666744-24d5e4a83350?auto=format&fit=crop&q=80&w=600',
    additionalImages: [],
    batchNumber: 'B1010',
    expiryDate: '2028-12-01',
    minStockLevel: 100,
    stockStatus: 'in-stock',
    healthConcern: 'Bone, Joint & Muscle',
    status: 'published',
  }
];

async function seed() {
  console.log('Seeding products...');
  
  const payloads = products.map(productData => ({
    name: productData.name,
    description: productData.description,
    price: productData.price,
    mrp: productData.mrp,
    discount: productData.discount,
    category: productData.category,
    subcategory: productData.subcategory,
    brand: productData.brandName,
    stock_quantity: productData.stockQuantity,
    image_url: productData.primaryImage,
    additional_images: productData.additionalImages,
    batch_number: productData.batchNumber,
    expiry_date: productData.expiryDate,
    min_stock_level: productData.minStockLevel,
    stock_status: productData.stockStatus,
    seo: { health_concern: productData.healthConcern },
    is_active: productData.status === 'published',
  }));

  const { error } = await supabase.from('products').insert(payloads);
  
  if (error) {
    console.error('Error inserting products:', error);
  } else {
    console.log(`Successfully added ${products.length} products.`);
  }
  process.exit(0);
}

seed();
